name = "notes-api"
main = "src/index.ts"
compatibility_date = "2023-09-01"

# Environment variables
[vars]
# Add environment variables here when needed

# KV Namespaces
# Uncomment when implementing KV storage
# [[kv_namespaces]]
# binding = "NOTES_KV"
# id = "..."
# preview_id = "..."

# Dev environment settings
[dev]
port = 8787
local = true 